### ISSUE TITLE
When is the release of version 2.2.5?

### ISSUE THREAD

**Issue by pinghe** [MarshallOfSound/electron-devtools-installer#104]
When is the release of version 2.2.5, I'm particularly interested in the feature that supports dynamically set userData path ( #88 )

**Comment by stanurkov** [comment]
Please release as now we get "7zip@0.0.6 not found" errors from npm

**Comment by mscoobby** [comment]
Please do release the version, we need the dynamically set userData feauter for our product.

**Comment by MarshallOfSound** [comment]
I'll be releasing a new version of this package later today although most changes should have been released a long time ago
