### ISSUE TITLE
New React Profiler

### ISSUE THREAD

**Issue by withintheruins14** [MarshallOfSound/electron-devtools-installer#106]
I can't seem to get the new React Dev Tools Profiler to install. To add it to any project, you simply upgrade your React-DOM version to 16.5. This was all that was needed in my React web apps. Any idea why this isn't working in Electron with this installer? Thanks!

**Comment by Gontte** [comment]
i have  the same situation😢

**Comment by peterdanis** [comment]
Remove your electron app data or run the `installExtension` method with `forceDownload` parameter (the second one, after extension name/id) set to `true` once.

Like `installExtension(REACT_DEVELOPER_TOOLS, true)`.

**Comment by MarshallOfSound** [comment]
As @peterdanis use the `forceDownload` parameter to, well, force a new and updated download
