### ISSUE TITLE
 Install IE tab extension error

### ISSUE THREAD

**Issue by 499689317** [MarshallOfSound/electron-devtools-installer#108]
When I want to install the IE tab plugin, I get an error, the specific error is as follows:
````
{ id: 'fmkadmapgofadopljbjfkapdkoienihi', electron: '>=1.2.1' }
Added Extension:  IE Tab
[271772:0725/185210.254:ERROR:CONSOLE(7785)] "Skipping extension with invalid URL: chrome-extension://ie-tab", source: chrome-devtools://devtools/bundled/shell.js (7785)
````
and my electron version is 4.2.7 run in windows10
I don't know if I don't support this plugin for some time or for other reasons.
Is there any way to solve it?

**Comment by MarshallOfSound** [comment]
That issue is upstream with Electron and should be fixed in v9
