### ISSUE TITLE
Abandoned repo - change maintainer?

### ISSUE THREAD

**Issue by ivancuric** [MarshallOfSound/electron-devtools-installer#109]
So there haven't been any updates in a year. There are also 5 PRs waiting, some that fix breaking issues in Windows.

**Comment by MarshallOfSound** [comment]
I detest issues like these "oh look a perfectly stable and functioning module hasn't been touched in a year, guess it must be abandoned".

Of your "5 PRs"
* 2 have failing tests
* 1 modifies a test file
* 1 has unresolved conflicts
* 1 has unresolved PR review comments (namely folks claiming it doesn't work for them)

I always make an effort to review, merge and publish PRs that folks put the time into making but currently I don't see what you think I should be doing differently.

If you want something fixed, raise a PR, don't declare a project abandoned...

**Comment by ivancuric** [comment]
https://github.com/MarshallOfSound/electron-devtools-installer/pull/92 is ready to be merged :)

**Comment by ivancuric** [comment]
So what about that PR then?
