### ISSUE TITLE
After first install, electron no longer runs

### ISSUE THREAD

**Issue by kyle-mcknight** [MarshallOfSound/electron-devtools-installer#110]
When I use the sample code exactly as provided to install redux tools so the REDUX_DEVTOOLS token, it works the first time. The extension is downloaded to %APPDATA%\<project>\extensions\<extension id> and my application runs and indeed I have the redux tools.

However, when I run my application a second time, the ready event is never fired and so the application doesn't even run at all. If I delete the extension folder and rerun the app, it works again. But then once again, it won't work as long as that folder is there.

My code is basically this
```
app.on('ready', appReady);

function appReady() {
//the first time through, this works.

//the second time through, the appReady method is never invoked unless I delete the extensions folder, and therefore showWindow is never invoked so the application never displays
    installExtension(REDUX_DEVTOOLS)
        .then((name) => showWindow)
        .catch((err) => console.log('An error occurred: ', err));
}
```

**Comment by jehugaleahsa** [comment]
@kyle-mcknight I ran into this same issue. Can you provide any information about this problem? It was only a problem when `productName` was set in the `package.json`.  I just commented out the code for now but would love a real solution.

**Comment by rob10e** [comment]
I have also run into this problem.

I have tried it with the react and redux extensions, both manually as per the documentation and using the extension loader. Deleting the electron cache directory for the app: C:\Users\<USER>\AppData\Roaming\<APPNAME> fixes it for one more run, then I have to delete it again to run it again.

I have found that Electron 5.0.11 not have this problem.

**Comment by kyle-mcknight** [comment]
> @kyle-mcknight I ran into this same issue. Can you provide any information about this problem? It was only a problem when `productName` was set in the `package.json`. I just commented out the code for now but would love a real solution.

Unfortunately I haven't figured out exactly what's causing it or how to fix it. Generally I simply delete the appdata that the devtools installer uses for extensions in %appdata%\<project name>\extensions\<extension name> and try to re-run it. Sometimes it works, sometimes it doesn't but i just keep doing it until it does. I haven't found out yet if it does this in production or not

**Comment by SebastienWae** [comment]
This is probably related to this issue [electron/electron#19468](https://github.com/electron/electron/issues/19468)

@LuminescentMoon solution is currently working [LuminescentMoon/electron-win10darktheme-workaround.ts](https://gist.github.com/LuminescentMoon/f7a180a6960d4d1b9b7e72acb1c77275)

**Comment by nathanvogel** [comment]
Same issue here (still)
@wmhilton's fix is considered better: https://github.com/electron/electron/issues/19468#issuecomment-549593139

**Comment by hgouveia** [comment]
Happened to me with `electron: 7.3.3` and `electron-devtools-installer: 3.1.1` ,

i was able to workaround it by replacing `app.on('ready', () => { /*...*/ });`  with `app.prependOnceListener('ready',  () => { /*...*/ })`
