### ISSUE TITLE
React tab not showing

### ISSUE THREAD

**Issue by WangDea** [MarshallOfSound/electron-devtools-installer#115]
Hello,
I'm using electron7.0.0, react16.11, electron-devtools-installer 2.2.4 on a debian computer without google-chrome.
I tried to install react dev tools using the following code:
`const  { default: installer, REACT_DEVELOPER_TOOLS } = require('electron-devtools-installer')
  installer(REACT_DEVELOPER_TOOLS).then(name => {
    console.log('added:', name)
  }).catch(console.log)`
after running the program I get "added: React Developer Tools" printed in the console (success).
Opening the Dev Tools I don't have a React tab.

what am I doing wrong?
tnx

**Comment by Lothindir** [comment]
What did you do to resolve the issue ? I am in the same situation as you...
