### ISSUE TITLE
Cannot read property 'net' of undefined (Electron 8 beta)

### ISSUE THREAD

**Issue by tommoor** [MarshallOfSound/electron-devtools-installer#117]
Attempt to upgrade to Electron `8.0.0-beta.2` I'm receiving this error.

https://github.com/MarshallOfSound/electron-devtools-installer/blob/master/src/utils.js#L11-L12

```
TypeError: Cannot read property 'net' of undefined
node_modules/electron-devtools-installer/dist/utils.js:34:16
```

**Comment by MarshallOfSound** [comment]
@tommoor This was because the `remote` module was disabled by default in electron 8. You should be using this module from the main process anyway and future versions of this module will **only** work from the main process
