### ISSUE TITLE
CI seems to be broken

### ISSUE THREAD

**Issue by ivancuric-sauna** [MarshallOfSound/electron-devtools-installer#118]
The [recent master PR merge](https://github.com/MarshallOfSound/electron-devtools-installer/commit/3e37415fe3b4c9dc4f669d643c455f28a8338c21) and a few other PRs seem to have gotten [stuck in the CI](https://travis-ci.org/MarshallOfSound/electron-devtools-installer/jobs/606279849?utm_medium=notification&utm_source=github_status):

```sh
0.01s$ export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
sh: 0: Can't open /etc/init.d/xvfb
The command "export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start" failed and exited with 127 during .
Your build has been stopped.
```

It started consistently breaking about 2 months ago: https://travis-ci.org/MarshallOfSound/electron-devtools-installer/builds/580131175

Any ideas what might have caused that?

**Comment by MarshallOfSound** [comment]
CI is being fixed in the `cleanup` branch that should be merged to master later today
