### ISSUE TITLE
First, first time installed extension always fails via missing manifest.json

### ISSUE THREAD

**Issue by cjones26** [MarshallOfSound/electron-devtools-installer#121]
Hi,

I've been attempting to utilize this project in order to install my React & Redux DevTools.  After deleting my ~/.config/Electron/extensions folder, I _always_ receive the following error on first launch, which always references the first extension in passed to `installExtension` (in this case, Redux DevTools was the first extension passed to `installExtension`):

> [1] Reading /home/users/.config/Electron/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd/manifest.json failed.
> [1] Error: ENOENT: no such file or directory, open '/home/users/.config/Electron/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd/manifest.json'
> [1]     at Object.openSync (fs.js:447:3)
> [1]     at Object.func (electron/js2c/asar.js:140:31)
> [1]     at Object.func [as openSync] (electron/js2c/asar.js:140:31)
> [1]     at Object.readFileSync (fs.js:349:35)
> [1]     at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
> [1]     at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
> [1]     at getManifestFromPath (electron/js2c/browser_init.js:4012:26)
> [1]     at Function.BrowserWindow.addExtension (electron/js2c/browser_init.js:4434:22)
> [1]     at Function.BrowserWindow.addDevToolsExtension (electron/js2c/browser_init.js:4466:40)
> [1]     at App.<anonymous> (electron/js2c/browser_init.js:4495:23)

Here is how my code looks for my Electron app's index.js:

```
const { app, BrowserWindow } = require('electron');
const {
  default: installExtension,
  REACT_DEVELOPER_TOOLS,
  REDUX_DEVTOOLS
} = require('electron-devtools-installer');
let win;

function createWindow() {
  win = new BrowserWindow({
    width: 800,
    height: 600,
    transparent: false,
    webPreferences: {
      // <--- (1) Additional preferences
      nodeIntegration: false,
      preload: __dirname + '/preload.js' // <--- (2) Preload script
    }
  });
  win.loadURL('http://localhost:3000'); // <--- (3) Loading react

  win.webContents.openDevTools();
  win.on('closed', () => {
    win = null;
  });
}

function installReactDevTools() {
  // Install React Devtools
  installExtension(REACT_DEVELOPER_TOOLS)
    .then(name => console.log(`Added Extension:  ${name}`))
    .catch(err => console.log('An error occurred: ', err));
}

function installReduxDevTools() {
  // Install Redux DevTools
  installExtension(REDUX_DEVTOOLS)
    .then(name => console.log(`Added Extension:  ${name}`))
    .catch(err => console.log('An error occurred: ', err));
}

app.on('ready', createWindow);
app.on('ready', installReduxDevTools);
app.on('ready', installReactDevTools);
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
app.on('activate', () => {
  if (win === null) {
    createWindow();
  }
});
```

I've tried several other ways to install the extensions (such as placing the createWindow in the fulfilled callback of installExtension), all of them failing the same way.  It almost seems like a race condition where Electron attempts to load the extension before the extension files exist.  After the first launch, everything is fine and both extensions show up in the DevTools window with no error.

Any thoughts would be appreciated.

Thanks!

-CJ

**Comment by MarshallOfSound** [comment]
This is fixed in latest code and will be fixed in the next release
