### ISSUE TITLE
Causes latest version of electron to hang

### ISSUE THREAD

**Issue by Reptarsrage** [MarshallOfSound/electron-devtools-installer#122]
Tested on 
Win 10 Version 10.0.18362 Build 18362
electron@7.1.6
electron-devtools-installer@2.2.4

Repro Steps:
1. Clone the quick start repo from here: [https://github.com/electron/electron-quick-start](https://github.com/electron/electron-quick-start)
2. Add `electron-devtools-installer@latest` and configure it in main.dev (code below)
3. Launch the program via `npm start`
4. Close the program by closing the window (NOTE: this bug does not happen if you kill the program via command line)
5. Try to reopen the program via `npm start`

**Expected Behavior**: The program should open with the installed extensions
**Actual Behavior**: The Program does not open at all

relevant code from `main.dev`:
```js
...

async function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  const { default: installExtension, REACT_DEVELOPER_TOOLS } = require('electron-devtools-installer');
  await installExtension(REACT_DEVELOPER_TOOLS);

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
    await createWindow(); 
});

...
```

Not sure if this is an issue with electron itself or this extension. To get the program working again delete the contents of `%AppData%\electron-quick-start` and run it again.

**Comment by b-zurg** [comment]
I narrowed it down to devtools extensions as well and it seems to be a known bug in electron 6+ with dark mode. (see: https://github.com/electron/electron/issues/19468)

I found that a specific file can be deleted to fix the issue and wrote a function to delete this file before startup. 
```js
...
const fs = require("fs");
...
const deleteDevToolsCacheIfDev = () => {
    if (process.platform === "win32") {
      const DevToolsExtensions = `${process.env.APPDATA}\\Electron\\DevTools Extensions`;
      try {
        fs.unlinkSync(DevToolsExtensions);
      } catch (_) {
        // noop
      }
    }
  }
```


I think a longer term fix for this issue has to come from the electron team.

**Comment by Reptarsrage** [comment]
Thanks for looking into it! Closing this issue as it's being worked on by the electron team instead
