### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by LucasArbre** [MarshallOfSound/electron-devtools-installer#124]
Starting a project with electron-forge:
An unhandled error has occurred inside Forge:
Failed to install modules: ["electron-devtools-installer@^2.1.0","react@^15.4.1","react-dom@^15.4.1","react-hot-loader@^3.0.0-beta.6"]

With output: Exited with status 1
Error: Failed to install modules: ["electron-devtools-installer@^2.1.0","react@^15.4.1","react-dom@^15.4.1","react-hot-loader@^3.0.0-beta.6"]

installing individually:
npm ERR! code E404
npm ERR! 404 Not Found: 7zip@0.0.6

**Comment by jmcrthrs** [comment]
Hey, I am also receiving this npm error.

Which platform are you on?

**Comment by g1eny0ung** [comment]
Same with me.

`Couldn't find package "7zip@0.0.6" required by "electron-devtools-installer@^2.2.4" on the "npm" registry.`

**Comment by LucasArbre** [comment]
> Hey, I am also receiving this npm error.
> 
> Which platform are you on?

Windows

**Comment by juancarlosfarah** [comment]
Seeing the same issue on macOS 10.15.3, running Yarn 1.22.0, Node 12.16.0. 

Looks like the package has been renamed on NPM to win-7zip.

https://github.com/fritx/win-7zip/issues/6

**Comment by jsheffers** [comment]
Just tested.  This has been fixed.
