### ISSUE TITLE
Can you add React to the project title?

### ISSUE THREAD

**Issue by leontepe** [MarshallOfSound/electron-devtools-installer#125]
I think it should state somewhere in the project title or readme that this is to install _React_ developer tools for Electron. Since there also are developer tools for Vue, this might be misleading.

**Comment by nklayman** [comment]
This plugin supports Vue as well, along with a bunch of other extensions.

**Comment by leontepe** [comment]
Oh, I'm sorry. Didn't look through the readme enough... my fault :(
