### ISSUE TITLE
[Request] BrowserView

### ISSUE THREAD

**Issue by Silvano14** [MarshallOfSound/electron-devtools-installer#129]
Is it possible add redux dev tools in a electron's browser view? 
Until now i can add devtools only in the main window.

**Comment by iamgbayer** [comment]
I would like also to add this in `webview` tag, what do you think?

**Comment by Silvano14** [comment]
Could be interesting, but the webview isn't deprecated yet? 
Seems that Electron wants remove many method about webview tag -> https://www.electronjs.org/docs/breaking-changes

**Comment by patarapolw** [comment]
Can someone update to attach to session object?

**Comment by johannesjo** [comment]
> Could be interesting, but the webview isn't deprecated yet?

The webview itself isn't deprecated as far as I can see. 

Was somebody able to make this work somehow?

**Comment by MarshallOfSound** [comment]
API is now on `session` so this works Out Of The Box
