### ISSUE TITLE
Electron v9.0.0

### ISSUE THREAD

**Issue by sirtimid** [MarshallOfSound/electron-devtools-installer#130]
Is there any plan to migrate to the new stable version of Electron?

`BrowserWindow.getDevToolsExtensions` and `BrowserWindow.addDevToolsExtension` are deprecated and will be removed.

**Comment by develerik** [comment]
I already opened a pull request to fix this (#131)

**Comment by DmitryMK** [comment]
There seems to be a different issue with Electron 9.x at the moment, which does not allow to use extensions, when loading your app using file:// or browserWindow.loadFile. It is not related to this repository, but it might help those who are facing the issue that devtools does not work in 9.x.

**Comment by develerik** [comment]
I'm using the vue devtools in my electron 9 project and they are working fine. In development I use 'browserWindow.loadUrl("file://...")`

**Comment by proto6** [comment]
I can confirm that redux dev tools do NOT work in Electron 9.0.4 but do work in 8.3.1

**Comment by khanh-bes** [comment]
react dev tools is not working either

**Comment by tom-james-watson** [comment]
With https://github.com/MarshallOfSound/electron-devtools-installer/pull/131 now being merged, this now looks like it's an upstream issue with electron and/or the extensions themselves - https://github.com/electron/electron/issues/23662

**Comment by petef19** [comment]
still not working on Electron 9.1.0 - I opened ticket [here](https://github.com/electron/electron/issues/24638)

**Comment by Keimeno** [comment]
It works on electron v9+ if you install the extensions after the `app.on "ready"` event, and when passing the following `installExtension` options `{ loadExtensionOptions: { allowFileAccess: true } }`

**Comment by MarshallOfSound** [comment]
Electron 9.0.0 is supported 👍
