### ISSUE TITLE
(electron) 'BrowserWindow.addDevToolsExtension' is deprecated and will be removed. Please use 'session.loadExtension' instead.

### ISSUE THREAD

**Issue by kingangelAOA** [MarshallOfSound/electron-devtools-installer#132]

**Comment by ZuBB** [comment]
@kingangelAOA we already have an ongoing PR for this thing -- https://github.com/MarshallOfSound/electron-devtools-installer/pull/131

**Comment by ZuBB** [comment]
to @MarshallOfSound: I would suggest to close this as dup

**Comment by songyuc** [comment]
Have this issue been resolved yet?

**Comment by bennymeg** [comment]
Seems that PR #131 did not fixed it.
I still have the warning with `electron-devtools-installer@1.3.1` & `electron@10.1.5`.

**Comment by MarshallOfSound** [comment]
This hasn't been a problem for quite a few releases
