### ISSUE TITLE
Support custom partition string for session

### ISSUE THREAD

**Issue by praneetrohida** [MarshallOfSound/electron-devtools-installer#134]
I have a use case where I have to install extensions for a session other than the default session in Electron. It would we great if the API took a session instance or a partition string as an argument to make this possible.

**Comment by nikwen** [comment]
To help with the spring cleaning, here's the list of PRs that have attempted to implement this feature:

- https://github.com/MarshallOfSound/electron-devtools-installer/pull/192
- https://github.com/MarshallOfSound/electron-devtools-installer/pull/209
- https://github.com/MarshallOfSound/electron-devtools-installer/pull/243
