### ISSUE TITLE
[Request] Support pixi.js inspector

### ISSUE THREAD

**Issue by 2n2n** [MarshallOfSound/electron-devtools-installer#144]
Hopefully this can be supported as well, currently using electron 8

https://github.com/bfanger/pixi-inspector

**Comment by fakob** [comment]
You can easily add the extension yourself using its ID, but it unfortunately does not work. See https://github.com/bfanger/pixi-inspector/issues/20
```
installExtension([
      REACT_DEVELOPER_TOOLS,
      REDUX_DEVTOOLS,
      'aamddddknhcagpehecnhphigffljadon', // PIXI_INSPECTOR
    ])
      .then((name) => console.log(`Added Extension:  ${name}`))
      .catch((err) => console.log('An error occurred: ', err));
```

**Comment by MarshallOfSound** [comment]
As per comment above, you can easily install any extension you want with the requisite ID
