### ISSUE TITLE
React developer tools sometimes can't be loaded

### ISSUE THREAD

**Issue by jwir3** [MarshallOfSound/electron-devtools-installer#147]
Apologies if this is something misconfigured with my environment or a misunderstanding on my part, but I'm seeing an issue where the `REDUX_DEVTOOLS` is injected into the electron instance, but `REACT_DEVELOPER_TOOLS` fails. Here's how we're loading the tools:

```
      installExtension([REDUX_DEVTOOLS)
        .then((name) => global.logger.info(`Added extension: ${name}`, {'class' : 'main'}))
        .catch((err) => console.log('An error occurred while trying to add redux devtools: ', err));

      installExtension(REACT_DEVELOPER_TOOLS)
        .then((name) => global.logger.info(`Added extension: ${name}`, {'class' : 'main'}))
        .catch((err) => console.log('An error occurred while trying to add react devtools: ', err));
```

And, when our application is launched, it responds with:
```
[09:45:25] [Main] [INFO] [main] Added react and redux developer tools extensions: Redux DevTools
```

and, then, later:
```
An error occurred while trying to add react devtools:  Error: Exited with code 9
    at ChildProcess.<anonymous> (/Users/<username>/Source/<project>/node_modules/cross-unzip/index.js:38:21)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

I discovered that, somehow, my react-developer-tools extension from Chrome had been uninstalled (I'm not sure how). If I reinstall the extension in the browser, then this error does not occur and the react devtools are loaded. My understanding, though, is that this project allows us to install devtools _without_ installing them in Chrome first, correct?

My system information:
```
Operating System: MacOS 10.15.6
React Devtools Version (Installed in Chrome): 4.8.2 (7/15/2020)
electron-devtools-installer Version: electron-devtools-installer@3.1.1
```

**Comment by KotoriK** [comment]
Same problem but with exit code 2
```
Error: Exited with code 2
    at ChildProcess.<anonymous> (C:\Users\Administrator.SVR-K\Documents\GitHub\rss-reader\node_modules\cross-unzip\index.js:38:21)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```
System Info:
Node v14.5
electron-devtools-installer@2.2.4

**Comment by CerratoA** [comment]
Any solution for this issue? facing the code 2 error

**Comment by sfilata** [comment]
I get a code 2 error. Is there any solution?

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
