### ISSUE TITLE
When to release the latest version?

### ISSUE THREAD

**Issue by chenzhutian** [MarshallOfSound/electron-devtools-installer#176]
Hi I see you have made many great update to the tool but still haven't release it.
Do you have any plan to release it?

**Comment by lzdyes** [comment]
@MarshallOfSound

**Comment by RoderickJDunn** [comment]
Not ideal but you can use `yarn add git+https://github.com/MarshallOfSound/electron-devtools-installer.git` to install the current build on master, for now. When the next version is released you can switch back to pulling from npm.
