### ISSUE TITLE
When passing an array of extensions, only the name of the final extension installed is returned

### ISSUE THREAD

**Issue by timsgardner** [MarshallOfSound/electron-devtools-installer#180]
For example, 
```typescript
  const installed = await installExtensions([REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS]);
  console.log('installed:', installed);
```
will print
```
installed: Redux DevTools
```
whereas the jsdocs suggest it should return the names of all the extensions:
https://github.com/MarshallOfSound/electron-devtools-installer/blob/19fd4dde8a8e3eb8a50ba4ca242bf3b52e878436/src/index.ts#L44

It looks like this is because the `reduce` in `install` throws away previous string values:

https://github.com/MarshallOfSound/electron-devtools-installer/blob/19fd4dde8a8e3eb8a50ba4ca242bf3b52e878436/src/index.ts#L64

**Comment by dimitropoulos** [comment]
as a workaround for anyone else encountering this, over on [insomnia](https://insomnia.rest/), we [did](https://github.com/Kong/insomnia/pull/3460):

```ts
  if (isDevelopment()) {
    try {
      const extensions = [REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS];
      const extensionsPlural = extensions.length > 0 ? 's' : '';
      const names = await Promise.all(extensions.map(extension => installExtension(extension)));
      console.log(`[electron-extensions] Added DevTools Extension${extensionsPlural}: ${names.join(', ')}`);
    } catch (err) {
      console.log('[electron-extensions] An error occurred: ', err);
    }
  }
  ```
