### ISSUE TITLE
Unable to Install React Devtools

### ISSUE THREAD

**Issue by luxifr** [MarshallOfSound/electron-devtools-installer#182]
I've tried installing React Devtools in my main.js as described in the readme:

```js
const {
  default: installExtension,
  REACT_DEVELOPER_TOOLS,
} = require('electron-devtools-installer')
```

```js
app.whenReady().then(() => {
  installExtension(REACT_DEVELOPER_TOOLS)
    .then(name => console.log(`Added Extension:  ${name}`))
    .catch(err => console.log('An error occurred: ', err))
  createWindow()
})
```

However, when starting my application, the devtools don't get installed but instead I get this console output:

```
(node:17712) ExtensionLoadWarning: Warnings loading extension at C:\Users\myusername\AppData\Roaming\myapp\extensions\fmkadmapgofadopljbjfkapdkoienihi:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'minimum_chrome_version'.
  Unrecognized manifest key 'update_url'.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

(Use `electron --trace-warnings ...` to show where the warning was created)
Added Extension:  React Developer Tools
```

I'm a bit at a loss on what to do... I've already removed the whole application folder in AppData to no avail.

**Comment by BlackHole1** [comment]
see: https://github.com/MarshallOfSound/electron-devtools-installer/issues/165

**Comment by Lothindir** [comment]
You'll have to manually delete those keys from `manifest.json` and the folder `_metadata`.

**Comment by seankovacs** [comment]
What worked for me is installing the package directly from git (e.g `yarn add git+https://github.com/MarshallOfSound/electron-devtools-installer.git`) and initializing it in code this way: 
`await installExtension(extensions, { loadExtensionOptions: { allowFileAccess: true }, forceDownload: false });`

The key for me was the `forceDownload: false`. With true, it wasn't working as I suspect something was failing during download?

**Comment by Londek** [comment]
> 
> 
> What worked for me is installing the package directly from git (e.g `yarn add git+https://github.com/MarshallOfSound/electron-devtools-installer.git`) and initializing it in code this way:
> `await installExtension(extensions, { loadExtensionOptions: { allowFileAccess: true }, forceDownload: false });`
> 
> The key for me was the `forceDownload: false`. With true, it wasn't working as I suspect something was failing during download?

Approved, this needs fix

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
