### ISSUE TITLE
[Discussion]: Should I fix ` unrecognized manifest key` in this project?

### ISSUE THREAD

**Issue by BlackHole1** [MarshallOfSound/electron-devtools-installer#200]
Many people in the community are currently experiencing the following error:

```
(node:22308) ExtensionLoadWarning: Warnings loading extension at xxx:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'minimum_chrome_version'.
  Unrecognized manifest key 'short_name'.
  Unrecognized manifest key 'update_url'.
  Permission 'activeTab' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
```

The reason for this error is due to the combination of chromium and electron

I have submitted a PR for the fix to electron and it has been merged as well, see:  https://github.com/electron/electron/pull/29695

~~However, it is not clear which version of this PR will be carried.~~ electron@v16.x

As a project affected by this issue do much, should we fix it temporarily in the project?

just like this: https://github.com/MarshallOfSound/electron-devtools-installer/pull/177

**Comment by BlackHole1** [comment]
This is a community project, so I wanted to discuss the feasibility with you all before submitting a PR.

@MarshallOfSound @BrunoS3D @dewinterjack @agentschmitt

**Comment by BlackHole1** [comment]
Here's a list of my statistics on encountering this problem:

https://github.com/MarshallOfSound/electron-devtools-installer/issues/197
https://github.com/MarshallOfSound/electron-devtools-installer/issues/182
https://github.com/MarshallOfSound/electron-devtools-installer/issues/149
https://github.com/MarshallOfSound/electron-devtools-installer/issues/143
https://github.com/MarshallOfSound/electron-devtools-installer/issues/141
https://github.com/MarshallOfSound/electron-devtools-installer/issues/165

**Comment by alisei-lab** [comment]
It would be great! Even tho it doesn't block anything it's always annoying to ignore warnings.

**Comment by agentschmitt** [comment]
i aggree thats annoying to ignore warnings and it seems the fix to electron wilkl be on v16 only so it would be nice to have the fix for devtools too.

**Comment by chase** [comment]
We're stuck on an older version of Electron for the time being, so I agree with @agentschmitt

I would like to see this merged still: https://github.com/MarshallOfSound/electron-devtools-installer/pull/177

**Comment by BlackHole1** [comment]
I have written another similar library to solve this problem

This library has the same capabilities as this one, which incidentally solves the https://github.com/MarshallOfSound/electron-devtools-installer/issues/205 problem

repo: https://github.com/BlackHole1/electron-devtools-vendor
npm: electron-devtools-vendor

**Comment by MarshallOfSound** [comment]
Advertising other modules to capitalize off of SEO of an existing module is bad form.  Please do not do so, I'd normally let it slide but doing it across multiple issues shows clear intent.

**Comment by BlackHole1** [comment]
> Advertising other modules to capitalize off of SEO of an existing module is bad form. Please do not do so, I'd normally let it slide but doing it across multiple issues shows clear intent.

👌🏻 sorry, I didn't mean to do that. you have a point.

**Comment by BlackHole1** [comment]
I would like to know what is the reason why you have not made any comments about https://github.com/MarshallOfSound/electron-devtools-installer/pull/177 and this issue so far?
Because 267 days have passed since I brought this up and you have not made any comments.
Although the project is personal to you and open source itself represents freedom.
Wouldn't it be more polite if you could respond to comments?

**I'm not moral coercion, I just have some questions about your long period of non-response.**
