### ISSUE TITLE
Manifest version 2 is deprecated, and support will be removed in 2023

### ISSUE THREAD

**Issue by progsmile** [MarshallOfSound/electron-devtools-installer#229]
Hello dear developers! Next warning appears on app start:

```
ExtensionLoadWarning: Warnings loading extension at /home/denys_klymenko/.config/MyAwesomeApp/extensions/fmkadmapgo
fadopljbjfkapdkoienihi:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
```
Could you bump Manifest version please? 
Thanks in advance!

Environment:
```
node.js: v16.15.0
electron: 20.3.0
electron-devtools-installer: 3.2.0
```

**Comment by hsqStephenZhang** [comment]
It seems that the V3 has been supported pretty well in the latest electron, so this issue becomes a matter of version choosing:

- [electron version>=27.0.0](https://github.com/facebook/react/issues/25843#issuecomment-1951774640) should be ok to use this package;
- if not, you should try this [work-around](https://github.com/facebook/react/issues/25843#issuecomment-1732226279), load the extension manually;

related discussions:

- [react #25843](https://github.com/facebook/react/issues/25843)
- [electron changelog of v27.0.0](https://github.com/electron/electron/releases/tag/v27.0.0)

**Comment by progsmile** [comment]
@hsqStephenZhang thanks for suggested solutions!
