### ISSUE TITLE
Error on renderer process

### ISSUE THREAD

**Issue by sobrinho** [MarshallOfSound/electron-devtools-installer#23]
```
ERROR in ./~/har-validator/lib/schemas/timings.json
Module parse failed: /Users/sobrinho/Developer/.../node_modules/har-validator/lib/schemas/timing
s.json Unexpected token (2:12)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:12)
    at Parser.pp$4.raise (/Users/sobrinho/Developer/.../node_modules/acorn/dist/acorn.js:2221:15
)
```

This error appears on renderer process, the documentation is not clear if the plugin must be called from main process or renderer process.

**Comment by sobrinho** [comment]
I'm able to make it work by calling the plugin from the main process and changing the usage to:

``` javascript
const x = require('electron-devtools-installer');

// from the electron boilerplate
function createWindow () {
  x.default(x.REACT_DEVELOPER_TOOLS)
    .then((name) => console.log(`Added Extension: ${name}`))
    .catch((err) => console.log('An error occurred: ', err));
}
```

Also, for some reason, the then function is not receiving the extension name, it only prints undefined.

**Comment by MarshallOfSound** [comment]
> ERROR in ./~/har-validator/lib/schemas/timings.json
Module parse failed: /Users/sobrinho/Developer/.../node_modules/har-validator/lib/schemas/timing
s.json Unexpected token (2:12)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:12)
    at Parser.pp$4.raise (/Users/sobrinho/Developer/.../node_modules/acorn/dist/acorn.js:2221:15
)

I don't see how this is related to this module.  `electron-devtools-installer` works from both the `main` and `renderer` processes and we have tests that prove it for each.  It looks like you are using some kind of bundler (webpack? electron-compiler?) and that is throwing the error. This module isn't even in the trace, what makes you think we are causing it?

**Comment by sobrinho** [comment]
Yes, I am using webpack.

The error only happens when requiring the electron-devtools-installer, otherwise it doesn't happen.

Maybe I'm misusing the package?

**Comment by rognoni** [comment]
@sobrinho Here works:
https://github.com/rognoni/0Face/blob/master/main.js

I have only to find a way to wait the and of the installation before open the window the first time!

**Comment by MarshallOfSound** [comment]
@sobrinho I'm going to close this out as a colleague informed me it is a problem with WebPack config not with this tool
