### ISSUE TITLE
Please state that this project is unmaintained in readme

### ISSUE THREAD

**Issue by Simon-Laux** [MarshallOfSound/electron-devtools-installer#235]
react dev tools are not working for me since electron 11, we have electron 22 right now and there are still not working.

Save us all some time and archive this repo or mark it as unmaintained at least, please @MarshallOfSound

**Comment by MarshallOfSound** [comment]
The issues you mentioned are completely unrelated to this package, Electron Dev Tools have been working for me up until Electron 23 (which we are currently looking into why it started failing).

Speaking as an Open Source Maintainer, you don't get to declare when a project is unmaintained.  And interestingly enough engaging with maintainers in that way is a fantastic way of getting yourself blocked everywhere 🤔

**Comment by Simon-Laux** [comment]
sorry for my tone, you're right that was completely out of place and I apologise for it, and seems like I was wrong... 🤦
react dev tools give me an error, I'll file a proper issue later, (though many issues are open without activity on this repo about the react dev tools, so my conclusion that there are unaddressed problems is not completely wrong, still my tone was.)
redux dev tools work, so it seems only to be an issue with the react dev tools.
