### ISSUE TITLE
Issue downloading extensions behind proxy

### ISSUE THREAD

**Issue by aaroncalderon** [MarshallOfSound/electron-devtools-installer#25]
Hi,

I have had an issue with  https://github.com/chentsulin/electron-react-boilerplate/issues/377

I am behind a corp proxy but my proxy settings work well (using cntlm).

For some reason I get and errro when I try to run **electron-react-boilerplate**'s `noder run dev` command.

I have tracked the error to https://github.com/MarshallOfSound/electron-devtools-installer/blob/master/src/downloadChromeExtension.js

```
{ Error: connect ECONNREFUSED 216.58.194.110:443
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '216.58.194.110',
  port: 443 }
```

My concern is if **electron-devtools-installer** is honoring the proxy settings I have set as environment variables?

**Comment by MarshallOfSound** [comment]
> My concern is if electron-devtools-installer is honoring the proxy settings I have set as environment variables?

It's not 😆 

I would however graciously accept a PR with an implementation of [`global-tunnel`](https://www.npmjs.com/package/global-tunnel) that you know works 👍

**Comment by MarshallOfSound** [comment]
@aaroncalderon Actually, according to the documentation of `request` it should automatically follow proxies set up in your environment variables.  Can you double check you have them set correctly?

**Comment by aaroncalderon** [comment]
@MarshallOfSound I have my proxy setup through __cntlm__. I use this setup for all my other packages (npm, git, brackets, VS Code, atom, bower...). I will troubleshoot `request` if I get a chance.

**Comment by oa414** [comment]
I also have the problem like it， just same as : https://github.com/SimulatedGREG/electron-vue/issues/37

I use ShadowSocks Proxy, and failed to load the extension,  use VPN is fine.

**Comment by MarshallOfSound** [comment]
@oa414 I might rewrite `electron-devtools-installer` to use the new `net` module if it's available.  That way it should auto-detect proxies a lot better

**Comment by el-davo** [comment]
Prob not a good idea but i managed to get them to install by adding this line right before the install

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

**Comment by MarshallOfSound** [comment]
@el-davo #35 should handle proxies for you now (if you are using Electron `1.4.5+`)

**Comment by xiaomizhou66** [comment]
？ 

```BASH
┏ Electron -------------------

  Failed to fetch extension, trying 4 more times

┗ ----------------------------

┏ Electron -------------------

  Failed to fetch extension, trying 3 more times

┗ ----------------------------

┏ Electron -------------------

  Failed to fetch extension, trying 2 more times

┗ ----------------------------

┏ Electron -------------------

  Failed to fetch extension, trying 1 more times

┗ ----------------------------

┏ Electron -------------------

  Failed to fetch extension, trying 0 more times

┗ ----------------------------

┏ Electron -------------------

  Unable to install `vue-devtools`:
   Error: net::ERR_CONNECTION_TIMED_OUT

┗ ----------------------------

```

**Comment by zoyopo** [comment]
> ？
> 
> ```shell
> ┏ Electron -------------------
> 
>   Failed to fetch extension, trying 4 more times
> 
> ┗ ----------------------------
> 
> ┏ Electron -------------------
> 
>   Failed to fetch extension, trying 3 more times
> 
> ┗ ----------------------------
> 
> ┏ Electron -------------------
> 
>   Failed to fetch extension, trying 2 more times
> 
> ┗ ----------------------------
> 
> ┏ Electron -------------------
> 
>   Failed to fetch extension, trying 1 more times
> 
> ┗ ----------------------------
> 
> ┏ Electron -------------------
> 
>   Failed to fetch extension, trying 0 more times
> 
> ┗ ----------------------------
> 
> ┏ Electron -------------------
> 
>   Unable to install `vue-devtools`:
>    Error: net::ERR_CONNECTION_TIMED_OUT
> 
> ┗ ----------------------------
> ```

u can use this  https://github.com/zoyopo/electron-skip-fetch-extension-after-failed
