### ISSUE TITLE
Consider a better zip lib

### ISSUE THREAD

**Issue by muntact** [MarshallOfSound/electron-devtools-installer#27]
The lib used for unzipping seems a tad sketchy.

It would probably make the installation a bit larger, but would it be worth looking at alternatives:
https://www.npmjs.com/package/unzip
https://www.npmjs.com/package/yauzl

**Comment by MarshallOfSound** [comment]
@muntact I tried **a lot** of unzip libraries before using these.  Basically Chromium extensions aren't ZIP files.  They are ZIP files with a tiny bit of extra header information.

For more information see: https://developer.chrome.com/extensions/crx

Basically normal ZIP libraries aren't equipped to handle this extra header information.  If you can find an alternative that works with the bonus header data PR's welcome 👍

**Comment by muntact** [comment]
Ahh, i made an assumption because i have been working around an unzip problem by using 7zip. 

If this is locked to a lib compatible with crx, this might be the best bet atm, as my basic search for unzipping crx didn't really net anything good looking either https://npms.io/search?q=crx

**Comment by fritx** [comment]
@MarshallOfSound thanks for using cross-unzip (brought so many downloads!!) 😃
