### ISSUE TITLE
Question: how to configure devtools?

### ISSUE THREAD

**Issue by elsueno** [MarshallOfSound/electron-devtools-installer#36]
I want to use the "ExtensionImmutable.js Object Formatter" extension (https://chrome.google.com/webstore/detail/immutablejs-object-format/hgldghadipiblonfkkicmgcbbijnpeog).

Installing it using electron-devtools-installer works flawlessly (const IMMUTABLEJS_OBJECT_FORMATTER = { id: 'hgldghadipiblonfkkicmgcbbijnpeog', electron: '^1.2.1' };)

When I start up electron I get the message "Immutable Object Formatter: Make sure to check 'Enable custom formatters' in the DevTools settings."

So how do I adjust that setting?

**Comment by MarshallOfSound** [comment]
I have no idea, it sounds like something extension specific so if possible you should ask them what API's they are using / where they store that setting 👍

**Comment by Slapbox** [comment]
![image](https://cloud.githubusercontent.com/assets/6835891/23833809/3c564044-0721-11e7-8ebb-eaa33b7bcb86.png)
