### ISSUE TITLE
Uncaught exception when installing React Developer Tools and Redux DevTools

### ISSUE THREAD

**Issue by markgillnz** [MarshallOfSound/electron-devtools-installer#38]
Electron-devtools-installer version: 2.1.0
Electron version: 1.4.12

I am seeing an uncaught exception when trying to install developer tools:
```
 Uncaught exception Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: C:\Users\FlyingSquad\AppData\Local\EMRConnect\app-1.0.1\resources\app.asar\node_modules\electron-devtools-installer\dist\utils.js:41:9.
        at ClientRequest.callIntoRenderer (C:\Users\FlyingSquad\AppData\Local\EMRConnect\app-1.0.1\resources\electron.asar\browser\rpc-server.js:199:19)
        at emitOne (events.js:96:13)
        at ClientRequest.emit (events.js:188:7)
        at URLRequest.ClientRequest.urlRequest.on (C:\Users\FlyingSquad\AppData\Local\EMRConnect\app-1.0.1\resources\electron.asar\browser\api\net.js:201:12)
        at emitOne (events.js:96:13)
        at URLRequest.emit (events.js:188:7)
```

Note that this issue does not occur when using version 2.0.1 of electron-devtools-installer

**Comment by MarshallOfSound** [comment]
This is due to us now using the electron `net` module and if you run the installer from the renderer process without letting it finish before you close the window it will throw this error.  Nothing we can do about it as it is an architectural thing with Electron

**Comment by markgillnz** [comment]
Expected errors such as this one shouldn't crash the application. They should be caught and handled appropriately.

**Comment by MarshallOfSound** [comment]
@markgillnz I can't handle this error, it's impossible due to the way Electron is architectured.  The context where this module is executed literally doesn't exist anymore.

Also uncaughtExceptions shouldn't cause an Electron app tp crash
