### ISSUE TITLE
Is the 7zip dependency used?

### ISSUE THREAD

**Issue by pzrq** [MarshallOfSound/electron-devtools-installer#44]
Is the [7zip dependency in package.json](https://github.com/MarshallOfSound/electron-devtools-installer/blob/5d1885d8a0e1a638930be1c8d8689107dd235e36/package.json#L50) used for anything?

7zip [does not show up in GitHub search (apart from the package.json)](https://github.com/MarshallOfSound/electron-devtools-installer/search?utf8=%E2%9C%93&q=7zip&type= ), while cross-unzip [does show up](https://github.com/MarshallOfSound/electron-devtools-installer/search?utf8=%E2%9C%93&q=cross-unzip&type= ):

<img width="843" alt="cross-unzip appears" src="https://cloud.githubusercontent.com/assets/1217010/24384579/922e3f4e-13b0-11e7-93c4-7acaa4faf850.png">

**Comment by MarshallOfSound** [comment]
It is a peer-dep of `cross-unzip` (at least for the version we use)

**Comment by pzrq** [comment]
Thanks @MarshallOfSound 👍
