### ISSUE TITLE
Exclude from production build

### ISSUE THREAD

**Issue by SirWindfield** [MarshallOfSound/electron-devtools-installer#45]
I am currently trying to remove your library from production builds since it is not needed. I wrapped the install statements:

```javascript
const installExtensions = async () => {
  if (process.env.NODE_ENV === 'development') {
    const extensions = ['REACT_DEVELOPER_TOOLS', 'REDUX_DEVTOOLS'];

    return Promise
      .all(extensions.map(name => install.default(install[name])))
      .catch(console.log);
  }
  return Promise.resolve();
};
```

For some odd reasons, the dependency still stays in production. Is it intended to?

**Comment by MarshallOfSound** [comment]
I mean, wrapping the install in a env check isn't going to magically make a dependency disappear?  You might be used to the world of webpack / FE bundlers where it would dissapear, but in normal node.js code that doesn't happen 😆

**Comment by MarshallOfSound** [comment]
The way most people do it is to make `electron-devtools-installer` a devDep and then try catch the require 👍

**Comment by SirWindfield** [comment]
I was using webpack, not sure we it still bundled it. Thought I might get the best help here. It is installed as dev dependency.

**Comment by MarshallOfSound** [comment]
@SirWindfield If you are using webpack with Electron (for whatever reason) then the code you would want is this.

```js
const installExtensions = async () => {
  if (process.env.NODE_ENV !== 'production') {
    const install = require('electron-devtools-installer');
    const extensions = ['REACT_DEVELOPER_TOOLS', 'REDUX_DEVTOOLS'];

    return Promise
      .all(extensions.map(name => install.default(install[name])))
      .catch(console.log);
  }
  return Promise.resolve();
};
```

**Comment by MarshallOfSound** [comment]
Ensure you have the webpack define plugin set up and working 👍

**Comment by SirWindfield** [comment]
I have, not sure why it doesn't actually remove the call. Even used `cross-env`. Sorry for bothering you :smile:
