### ISSUE TITLE
Package v2.1.0 in npmjs is stale

### ISSUE THREAD

**Issue by 3n-mb** [MarshallOfSound/electron-devtools-installer#47]
In particular, right now in main branch, with version 2.1.0, [index.js](https://github.com/MarshallOfSound/electron-devtools-installer/blob/master/src/index.js) is 94 lines long, but same file, coming from npm is 86 lines. Missing are lines:
```javascript
export const CYCLEJS_DEVTOOL = {
  id: 'dfgplfmhhmdekalbpejekgfegkonjpfp',
  electron: '^1.2.1',
};
```
And, as a result `CYCLEJS_DEVTOOL` is undefined.
I guess, update of npm is needed, by bumping version to 2.1.1, to make npm accept fresh upload.

On the side, *thank you very much* for this package. Love it.

**Comment by MarshallOfSound** [comment]
The cycles or was merged after the last release.  This is expected until the next version bump which is normally at my discretion and only done when i have time to deal with potential new bugs after a relesse
