### ISSUE TITLE
Can't load extension over HTTPS

### ISSUE THREAD

**Issue by danieltrolezi** [MarshallOfSound/electron-devtools-installer#52]
Hi!

Part of my app loads a page over HTTPS. That page has some React.js in it and I need to debug something that is going on there.

The problem is: the React Devtools Extension is added, but won't load because the page is loaded over HTTPS:

```
Mixed Content: The page at 'https://...' was loaded over HTTPS, but requested an insecure script 'chrome-extension://react-developer-tools/build/backend.js'. This request has been blocked; the content must be served over HTTPS.
```

Is there anything that I can do to load the extension over HTTPS as well?
Thanks.

**Comment by MarshallOfSound** [comment]
@danieltrolezi `chrome-extension://` should already be considered secure but you can probably call `webFrame.registerUrlSchemeAsSecure` on `chrome-extension` and it should accept the protocol request 👍

**Comment by danieltrolezi** [comment]
Works like a charm! Thank you so much!
