### ISSUE TITLE
7zip-lite folder

### ISSUE THREAD

**Issue by CzBuCHi** [MarshallOfSound/electron-devtools-installer#55]
for some reason when executing this code in electron main:
```js
const { default: installExtension, REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS, REACT_PERF } = require('electron-devtools-installer');

installExtension(REACT_DEVELOPER_TOOLS).then((name) => console.log(`Added Extension: ${name}`)).catch((err) => console.log('An error occurred: ', err));
installExtension(REDUX_DEVTOOLS).then((name) => console.log(`Added Extension: ${name}`)).catch((err) => console.log('An error occurred: ', err));
installExtension(REACT_PERF).then((name) => console.log(`Added Extension: ${name}`)).catch((err) => console.log('An error occurred: ', err));
```
i get 'file not found' error for `[directory where electron main is]/7zip-lite/7z.exe`  

i was able to fix this simply by copying `node_modules/7zip/7zip-lite` folder over there - then electorn successfully installs all 3 tools and error goes away even if i remove copied 7zip-lite folder.

im guessing, that somewhere in code u have wrong path to 7z.exe - not pointing to node_modules ...

**Comment by justin-calleja** [comment]
I get a similar issue (probably because on Mac, it's `7zip/index.js` instead of `7zip-lite/7z.exe`).

You just need to import the default exported value for this to happen:

```js
  const { default: installExtension } = require('electron-devtools-installer')
```

**Comment by killerspaz** [comment]
@CzBuCHi are you using webpack or any bundler that is including `electron-devtools-installer` in the bundle? That was my issue, as `__dirname` resolves to the bundle location, instead of the source of this module.

If you use webpack, check out [webpack-node-externals]( https://github.com/liady/webpack-node-externals).

**Comment by CzBuCHi** [comment]
@killerspaz yea ... i was using webpack for mian and renderer, but as my pet project is dont have enouch time for it right now ... :( 
im thining use webpack only for renderer and main compile with tsc only ...

**Comment by psychobolt** [comment]
I am using Babel with webpack and __dirname was always resolving to '/'. The fix for me is to add to the webpack config:

`node: {
    __dirname: true
  }`

On official [documentation](https://webpack.js.org/configuration/node/#node-__dirname
)

**Comment by derek126** [comment]
Setting node: { __dirname: true } in my project has a lot of other issues and this is not possible. Any other solutions?

**Comment by NearAutomata** [comment]
This issue hasn't been resolved in over a year now and I can't use the `node: { __dirname: true }` "fix". Any update on this one @MarshallOfSound?

**Comment by MarshallOfSound** [comment]
I don't have time to look into every issue and this one is a weboack config specific issue with a known workaround.  If someone wants to fix it good on them... But I don't have the time to

**Comment by starriv** [comment]
use [webpack-node-externals](https://github.com/liady/webpack-node-externals) can resolve this issue

**Comment by motin** [comment]
Possible fix, based on not using the buggy 7-zip package at all: https://github.com/MarshallOfSound/electron-devtools-installer/pull/92

**Comment by jdoubleu** [comment]
This issue might have been related to https://github.com/electron/electron/issues/8206
