### ISSUE TITLE
__REACT_DEVTOOLS_GLOBAL_HOOK__ is undefined

### ISSUE THREAD

**Issue by cl4ws0n** [MarshallOfSound/electron-devtools-installer#57]
I'm trying to use this with the react dev tools and the preact dev tool wrapper... 

Preact's dev tool wrapper calls this function when it's module is added but never gets past the first if statement
```javascript
function initDevTools() {
  if (typeof __REACT_DEVTOOLS_GLOBAL_HOOK__ === 'undefined') {
    // React DevTools are not installed
    return;
  }
  //...
```

I've added devtools-installer as a dependency and in my main process, I've got

```javascript
import installDevTool,
       { REACT_DEVELOPER_TOOLS } from "electron-devtools-installer"
```
and then in my create window function I call
```javascript
  //...
  installDevTool(REACT_DEVELOPER_TOOLS)
   .then((n) => {
     console.log(`Added extension ${ n }`)

     active.loadURL(url.format({
       pathname: file,
       protocol: "file:",
       slashes: true
     }))

     console.log(BrowserWindow.getDevToolsExtensions())
   })
   .catch((err) => console.warn("Error loading extension", err))
```
I get back
```
Added extension React Developer Tools
{ 'React Developer Tools': { name: 'React Developer Tools', version: '2.4.0' } }
```
but `__REACT_DEVTOOLS_GLOBAL_HOOK__` remains undefined in the renderer process. Am I doing something wrong?

**Comment by cl4ws0n** [comment]
Turns out this will happen with any extension if you are sandboxing the `BrowserWindow`.

**Comment by Slapbox** [comment]
@MarshallOfSound is this also expected when loading the app over `app://` protocols and/or when `contextIsolation` is enabled?

It's really difficult to work without React Devtools being available in our development builds.
