### ISSUE TITLE
Throws an error when attempting to write ID map

### ISSUE THREAD

**Issue by karl** [MarshallOfSound/electron-devtools-installer#58]
When using `electron-devtool-installer` I get the following error:

```
Error adding extension: { Error: ENOENT: no such file or directory, open '/Users/karl/Library/Application Support/Electron/extensions/IDMap.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at /Users/karl/example/index.js:48788:18
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/karl/Library/Application Support/Electron/extensions/IDMap.json' }
```

It looks like this is thrown from https://github.com/MarshallOfSound/electron-devtools-installer/blob/master/src/index.js#L48

It seem like the `extensions` directory does not exist, so the write to `IDMap.json` fails. Do you think that `electron-devtools-installer` should create the directory first?

Unfortunately I don't have a repo to recreate this, I'm still new to using Electron so I'm not sure how to create a slimmed down example that shows this. I thought it was still worth raising the bug.

**Comment by MarshallOfSound** [comment]
@karl I just looked into this and afaics this should be impossible 😆 as `downloadChromeExtension` creates the folder.  Without a repro or failing test case idk what's going on

**Comment by karl** [comment]
Thanks for looking into this @MarshallOfSound!

You're right that `downloadChromeExtension` should be creating the folder! I didn't spot that when I was looking for a possible cause.

I'll do some more digging on my side and re-open this if I'm able to provide steps to reproduce.

**Comment by chbdetta** [comment]
@karl Did you find the reason that this exception is thrown?

**Comment by karl** [comment]
I didn’t I’m afraid, I moved on to other things and I don’t think the error occurs any more for me!
