### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by dland512** [MarshallOfSound/electron-devtools-installer#61]
Once the plugin is installed, is it possible to uninstall it?

**Comment by Hammster** [comment]
For Windows you can remove the extension folder of electron inside appdata
"%appdata%\Roaming\Electron\extensions" under linux and mac this should be in the representative dotfile folders.

**Comment by obiwanjacobi** [comment]
And if that doesn't work? After having this installed for a bit and then uninstalled -as well as removing the AppData electron folder my app still screams it needs this module at startup. I have used npm list but I cannot see any left over dependency. Any ideas?

**Comment by natew** [comment]
I think this is a question for having an API to remove it at runtime, after you've run install.

**Comment by MarshallOfSound** [comment]
You can use Electron's apis for listing and removing extensions to do this

**Comment by m4major** [comment]
use it after electron ready (app.on('ready'....)
BrowserWindow.removeDevToolsExtension('React Developer Tools');
