### ISSUE TITLE
Redux devtools won't load on Linux, maybe due to missing installation option

### ISSUE THREAD

**Issue by eric-burel** [MarshallOfSound/electron-devtools-installer#65]
Hi,

Even after a successul install, `window.__REDUX__DEVTOOLS_EXTENSION_COMPOSE__` is undefined, at least on Linux (the issue does not seem to appear on Windows).

This seems to be due to the following issue: [https://github.com/zalmoxisus/redux-devtools-extension/issues/219](https://github.com/zalmoxisus/redux-devtools-extension/issues/219)

However, when using the installer, I don't have access to the module options (or at least I did'nt find them ?). Is it possible to make sure that the `Allow access to file url` option is ticked when installing React Devtools ?

**Comment by mrobrian** [comment]
Having the same issue on Windows. The Redux dev tools aren't usable, including the Redux tab in dev tools, due to the file URL option not being set.

**Comment by MarshallOfSound** [comment]
This isn't specific to this module, you should try repro this upstream with plain Electron and report to electron/electron

**Comment by eric-burel** [comment]
Hi, this is old but if I remember correctly the underlying question was how to tick options when installing a Chrome plugin. I understand that this may be undoable but that's not  the module developer fault either :/ If options can't be passed to the installer, maybe be this request should be passed higher up to Chrome devs? 

Again this is old so not sure whether it's already doable or not nowadays
