### ISSUE TITLE
win7 build 7zip ENOENT

### ISSUE THREAD

**Issue by ibyteyou** [MarshallOfSound/electron-devtools-installer#69]
i'm trying install vueTools on build version.
boilerplate - https://github.com/SimulatedGREG/electron-vue (webpack)

```
C:\Users\Averia\AppData\Local\Programs\averia-elab\resources\app.asar\node_modules\electron-log\renderer.js:34
[23:41:04.519] Unable to install `vue-devtools`: => Error: spawn
C:\Users\Averia\AppData\Local\Programs\averia-elab\resources\app.asar\node_modules\7zip\7zip-lite\7z.exe
ENOENT at exports._errnoException (util.js:1050:11) at
Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:367:16) at
_combinedTickCallback (internal/process/next_tick.js:80:11) at
process._tickCallback (internal/process/next_tick.js:104:9)
(anonymous)@C:\Users\Averia\AppData\Local\Programs\averia-elab\resources\app.asar\node_modules\electron-log\renderer.js:34
```

physical on the disk has:
- file app.asar (~189mb)
- path app.asar.unpacked (include node_modules/7zip/7zip-lite/7z.exe)

if you can, please make condition:
```
 if (!existSync(app.asar\node_modules\7zip\7zip-lite\7z.exe))
	use app.asar.unpacked\node_modules\7zip\7zip-lite\7z.exe
```
i trying understand this problem, but unsuccessfully(

**Comment by ddebarros** [comment]
what worked for me was adding an alias for 7zip in my webpack config file.

`yarn add -D win-7zip` and  in your config add 

`alias: {
      '7zip': path.resolve(__dirname, 'node_modules/win-7zip/index.js'),
}`

**Comment by josephbuchma** [comment]
@ddebarros can you please specify where exactly this alias should be added ? Does not seem to work for me

**Comment by jdpigeon** [comment]
Throwing this alias into Webpack resolve object doesn't seem to work for me

**Comment by jdpigeon** [comment]
Only way I'm able to workaround this for now is to copy the `7zip-lite` folder from node_modules into the app folder.

I can also confirm this is only an issue for Windows. Same project builds fine on Linux

**Comment by OliverRadini** [comment]
@jdpigeon That sounds like a useful workaround - though I can't find any reference to the `7zip-lite` folder you mention. Are you able to provide some more detail on where that may be found?

**Comment by jdpigeon** [comment]
@OliverRadini, I went back and took a look at that project. `7zip-lite` is a subdirectory of `7zip`, located at `electron-project/node_modules/7zip/7zip-lite`.

It's a bit of a hack, but try just moving that folder into your app folder. I think the issue here is that 7zip is being excluded either by webpack or electron-builder

**Comment by OliverRadini** [comment]
@jdpigeon Many thanks! I'll give that a try and see if it helps

**Comment by semireg** [comment]
I've got a two package.json project (via react boilerplate) and I came to this issue via google search for "error spawn electron 7z.exe ENOENT." This seemed to happen to me because I wrongfully added a native module to the project ./package.json, uninstalled it there, then installed instead to the app/package.json, but never ran "npm install" again from ./ to ... hmm, clear things up.

**Comment by Slapbox** [comment]
Copying 7zip-lite into `MY_PROJECT_ROOT/app` worked great!

**Comment by nattyrice** [comment]
Just had this issue.  What fixed it for me was setting:
```
  node: {
    __dirname: true
  }
```
in my `webpack.config.js`

I hope it helps!

**Comment by MarshallOfSound** [comment]
This is a webpack config issue, see the above for the standard webpack config required to make this kind of stuff work ☝️

**Comment by sminodonte** [comment]
Another solution, very easy,  is use the module 7zip-bin and change in the file index.js the rows:

```
  else if (process.platform === "win32") {
    return path.join(__dirname, "win", process.arch, "7za.exe")
  }
```

whit theses:
```

  else if (process.platform === "win32") {
    return path.join(".\\", "win", process.arch, "7za.exe")
  }
```
