### ISSUE TITLE
Extension isn't updating?

### ISSUE THREAD

**Issue by funwithtriangles** [MarshallOfSound/electron-devtools-installer#76]
I'm getting this console error when adding React DevTools:

**Warning: The installed version of React DevTools is too old**

My feeling is that I have a cached version of the extension installed somewhere that isn't updating. Any thoughts? On OSX.

**Comment by nukeop** [comment]
I'm getting this on GNU/Linux as well.

**Comment by yourfavorite** [comment]
I too am having this issue on OSX. I tried uninstalling electron-devtools-installer and reinstalling but still get the error.

**Comment by MarshallOfSound** [comment]
The extensions are cached in `~/Library/Application\ Support/Electron/extensions` on macOS and the equivalent on all other platforms.  Delete it their to uninstall and then it will be redownloaded next time 👍
