### ISSUE TITLE
net::ERR_TUNNEL_CONNECTION_FAILED

### ISSUE THREAD

**Issue by jeeftor** [MarshallOfSound/electron-devtools-installer#77]
I'm using this package as part of the Electron/Vue.js template.

Its called via:

```
// Install `vue-devtools`
require('electron').app.on('ready', () => {
  
  let installExtension = require('electron-devtools-installer')
  installExtension.default(installExtension.VUEJS_DEVTOOLS)
    .then(() => {})
    .catch(err => {
      console.log('Unable to install `vue-devtools`: \n', err)
    })
})
```

And i'm getting the following error.

>Unable to install `vue-devtools`:
   Error: net::ERR_TUNNEL_CONNECTION_FAILED

* I am behind a corporate firewall 
* The firewall does SSL Inspection

I'm unsure how to diagnose the issue.  

The command `yarn add  @vue/devtools` seems to work fine so I'm pretty sure the tools _should_ be able to be installed.

My yarn config has `  'strict-ssl': false,` set

Any ideas what else to try or how to get this working?

Thanks!

**Comment by MarshallOfSound** [comment]
This is some kind of proxy issue that is separate from this module, we literally just use the `net` module from Electron (which is Chromium's network stack) to make the download request.
