### ISSUE TITLE
Uncaught TypeError: this.on is not a function

### ISSUE THREAD

**Issue by javaxiu** [MarshallOfSound/electron-devtools-installer#79]
flowing the [Usage](https://github.com/MarshallOfSound/electron-devtools-installer#usage)，and console error show this
`Uncaught TypeError: this.on is not a function`
![image](https://user-images.githubusercontent.com/4281225/39342077-c7096d44-4a08-11e8-8a75-7bfef5d5eed0.png)

version info : React16.0, electron 1.4.6

**Comment by MarshallOfSound** [comment]
Electron `1.4.6` is **beyond** unsupported, please update to the latest Electron version, you are putting you and your users at risk by using a version that old.

Also, run this module from the main process for best experience 👍
