### ISSUE TITLE
React Dev Tools tab is missing

### ISSUE THREAD

**Issue by derek126** [MarshallOfSound/electron-devtools-installer#82]
My code is as follows:
~~~~
  private installExtensions = async () => {
    const extensions = [REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS];

    if (!BrowserWindow.getDevToolsExtensions().hasOwnProperty("devtron")) {
      BrowserWindow.addDevToolsExtension(path.join(__dirname, "..", "..", "node_modules", "devtron"));
    }

    await Promise.all(
      extensions.map((extension) => installExtension(extension)
      .then((name) => debug("Added Extension: " + name))
      .catch((err) => error("An error occurred: ", err)))
    );
  }
~~~~

The redux dev tools tab shows up in the Chromium dev tools, but React does not. Anyone else experiencing this?

**Comment by derek126** [comment]
`
  private readonly installExtensions = (): void => {
    if (!BrowserWindow.getDevToolsExtensions().hasOwnProperty("devtron")) {
      BrowserWindow.addDevToolsExtension(path.join(__dirname, "..", "node_modules", "devtron"));
    }

    installExtension(REACT_DEVELOPER_TOOLS)
    .then((name: string) => info(`Added Extension: ${name}`))
    .catch((err: string) => error(`An error occurred: ${err}`));

    installExtension(REDUX_DEVTOOLS)
    .then((name: string) => info(`Added Extension: ${name}`))
    .catch((err: string) => error(`An error occurred: ${err}`));
  }`

Just to follow up, Redux works fine. My dev console still says to install react dev tools for a better experience. I do see that adding the extensions passed in my log though.

**Comment by ajmacd** [comment]
I can see both React and Redux tabs using Electron `2.0.3`, but don't see either using `3.0.0-beta.1`. 🤔

**Comment by MarshallOfSound** [comment]
@ajmacd Probably an issue in the 3.0 beta, can you raise upstream?

**Comment by ajmacd** [comment]
Good point! I can confirm it is, after attempting the manual installation method. Filed here:
https://github.com/electron/electron/issues/13408

@derek126 perhaps a silly question, but do you have React components mounted on the page you're testing with? The React tab only shows up in that case (while the Redux tab shows up regardless).
