### ISSUE TITLE
Extensions only loaded on reload of renderer window

### ISSUE THREAD

**Issue by ksjogo** [MarshallOfSound/electron-devtools-installer#84]
The extension will only register their hooks on the top window after a reload of the renderer window is forced after their installation. Otherwise they will show the message for being installed but are not available otherwise.

**Comment by Ajeey** [comment]
+1

**Comment by Ajeey** [comment]
@MarshallOfSound Any update on this?

**Comment by warpdesign** [comment]
I am having the same problem.

**Comment by aesqe** [comment]
This works for me:

1. call installExtension on app ready
2. show BrowserWindow on 'ready-to-show'

```javascript
const { app, BrowserWindow } = require('electron');
const { default: installExtension, REACT_DEVELOPER_TOOLS } = require('electron-devtools-installer');

let mainWindow = null;

app.on('ready', () => {
  mainWindow = new BrowserWindow({
    show: false,
  });

  mainWindow.loadURL(`file://${__dirname}/src/index.html`);

  installExtension(REACT_DEVELOPER_TOOLS)
    .then((name) => console.log(`Added Extension:  ${name}`))
    .catch((err) => console.log('An error occurred: ', err));

  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
    mainWindow.openDevTools();
  });
});
```

**Comment by jwir3** [comment]
I'm actually seeing a slightly different issue - after reloading, the Components tab is empty. It shows up initially, but if I perform a CMD+R to refresh the page, the React Dev Tools are no longer usable.

**Comment by MarshallOfSound** [comment]
This is a race condition, ensure that `installExtension` has resolved before creating your windows, otherwise a reload is required
