### ISSUE TITLE
Code executed on import breaks tests

### ISSUE THREAD

**Issue by aeons** [MarshallOfSound/electron-devtools-installer#86]
We have some tests that do not directly interact with `electron-devtools-installer`, but imports a file that import this package.

Due to the code run on import in `index.js`, our tests errors out, since `electron.app` doesn't exist.

Specifically [this line](https://github.com/MarshallOfSound/electron-devtools-installer/blob/master/src/index.js#L12), which errors out on [this line](https://github.com/MarshallOfSound/electron-devtools-installer/blob/master/src/utils.js#L7) with `Cannot read property 'getPath' of undefined`.

**Comment by MarshallOfSound** [comment]
This sounds like a problem with your usage of this module.  It is not intended to work in a non-electron environment.

If you want this to work you will need to stub out the appropriate Electron API's 👍

**Comment by aeons** [comment]
The problem with stubbing them is that the code is run when *imported*, so it fails before the stubs or mocks can be set up.
