### ISSUE TITLE
Can't resolve './downloadChromeExtension' in .\node_modules\electron-devtools-installer\dist

### ISSUE THREAD

**Issue by Leskd** [MarshallOfSound/electron-devtools-installer#90]
ERROR in ./node_modules/electron-devtools-installer/dist/index.js
Module not found: Error: Can't resolve './downloadChromeExtension' in 'E:\git\one-project\node_modules\electron-devtools-installer\dist'
 @ ./node_modules/electron-devtools-installer/dist/index.js 26:31-67
 @ ./app/main/main.ts

 ./node_modules/electron-devtools-installer/dist/index.js
Module not found: Error: Can't resolve './utils' in 'E:\git\one-project\node_modules\electron-devtools-installer\dist'
 @ ./node_modules/electron-devtools-installer/dist/index.js 30:13-31
 @ ./app/main/main.ts

help me, plz

**Comment by Leskd** [comment]
electron-devtools-installer: 2.2.4
OS: win10

**Comment by WampirenoK** [comment]
same for me
OS: Ubuntu 18.04

**Comment by WampirenoK** [comment]
I've use `webpack` for bundling, so in my case I solved this like that:
```js
const webpackConfig = {
  resolve: {
    extensions: ['.js', /* other extensions */]
  },
  // other webpack configurations
```

**Comment by MarshallOfSound** [comment]
This is a webpack configuration issue, not specific to `electron-devtools-installer`
