### ISSUE TITLE
Where should installer be called?

### ISSUE THREAD

**Issue by JuanCaicedo** [MarshallOfSound/electron-devtools-installer#96]
Hi there! I'm having trouble figuring out where to run this script from 😅

I'm using this tool with nativefier, to address https://github.com/jiahaog/nativefier/issues/207

## Behavior
I tried to run the example code as a node script. This required me to install `electron` (which I installed locally). After that, I see the following error
```
/Applications/node_modules/electron-devtools-installer/dist/utils.js:27                                                                                                             [1/651]
  var savePath = (_electron.remote || _electron2.default).app.getPath('userData');
                                                              ^

TypeError: Cannot read property 'getPath' of undefined
    at getPath (/Applications/node_modules/electron-devtools-installer/dist/utils.js:27:63)
    at Object.<anonymous> (/Applications/node_modules/electron-devtools-installer/dist/index.js:40:59)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Applications/CCI-slack/react-devtools.js:1:124)
```

## Proposed fix
Given there's just something wrong in my environment (I'm assuming I'm writing this code in wrong place) then it we could add a section to the documentation explaining where that code should be.

## Extra info
FWIW, the result of `(_electron.remote || _electron2.default)` is a string path 😀

**Comment by kALLEBALIK** [comment]
electron-devtools-installer is a node module for electron and needs to be called inside electron after the app is ready.

**Comment by nklayman** [comment]
Call it inside of the `app.on('ready')` event listener.

```javascript
app.on('ready', async () => {
  installDevtools(...)
  ...
});

**Comment by wmhilton** [comment]
> Call it inside of the app.on('ready') event listener.

That's the magic puzzle piece that's missing from the README! Thanks!

**Comment by nk1tz** [comment]
Thank you @nklayman !
This would go a long way on if added to the README.
:+1:

**Comment by MarshallOfSound** [comment]
Added this info to the README and more clarity coming in the next version
