### ISSUE TITLE
Can't not open file "net.js": not found

### ISSUE THREAD

**Issue by yeongjet** [MarshallOfSound/electron-devtools-installer#98]
it reported error like this:

![image](https://user-images.githubusercontent.com/7941297/50637421-f1ee1800-0f94-11e9-9ba0-67ac7d71cf57.png)

Maybe I had just upgrade electron to 4.0 ? It run successful if doesn't import electron-devtools-installer

**Comment by MarshallOfSound** [comment]
This is an issue with your install of Electron not with `electron-devtools-installer` itself
